--MSSV: 22127293
--HOTEN: DƯƠNG TRUNG NGHĨA
--LOP: 22CLC05
--DE:

CREATE DATABASE QLY_BAIHAT
GO
USE QLY_BAIHAT
GO
--TAO BANG, KHOA CHINH, RBDL
CREATE TABLE BAIHAT
(
	IDTheLoai varchar(10),
	IDBaiHat varchar(10),
	TenBaiHat nvarchar(30) UNIQUE,
	IDTacGia int,
	CONSTRAINT PK_BAIHAT PRIMARY KEY (IDTheLoai,IDBaiHat)
)

CREATE TABLE THELOAI
(
	IDTheLoai varchar(10) PRIMARY KEY,
	TenTheLoai nvarchar(30),
	IDBaiHatTieuBieu varchar(10),
	IDTheLoaiCha varchar(10),
)

CREATE TABLE TACGIA
(
	IDTacGia int PRIMARY KEY,
	HoTen nvarchar(30),
	IDTheLoaiSoTruongNhat varchar(10),
	IDBaiHatTieuBieuNhat varchar(10),
)

--TAO KHOA NGOAI

ALTER TABLE BAIHAT
ADD CONSTRAINT FK_BH_TL
FOREIGN KEY (IDTheLoai)
REFERENCES THELOAI(IDTheLoai)

ALTER TABLE BAIHAT
ADD CONSTRAINT FK_BH_TG
FOREIGN KEY (IDTacGia)
REFERENCES TACGIA(IDTacGia)

ALTER TABLE THELOAI
ADD CONSTRAINT FK_TL_BH
FOREIGN KEY (IDTheLoaiCha,IDBaiHatTieuBieu)
REFERENCES BAIHAT(IDTheLoai,IDBaiHat)

ALTER TABLE TACGIA
ADD CONSTRAINT FK_TG_BH
FOREIGN KEY (IDTheLoaiSoTruongNhat,IDBaiHatTieuBieuNhat)
REFERENCES BAIHAT(IDTheLoai,IDBaiHat)

--NHAP LIEU
INSERT INTO THELOAI(IDTheloai,TenTheLoai)
VALUES ('TL01',N'Nhạc trữ tình'),
('TL02',N'Nhạc cách mạng'),
('TL00',N'Nhạc Việt Nam')


INSERT INTO BAIHAT(IDTheloai,IDBaiHat,TenBaiHat)
VALUES ('TL01','BH01',N'Ngẫu hứng lý qua cầu'),
('TL01','BH02',N'Chuyến đò quê hương'),
('TL02','BH01', N'Du kích sông Thao'),
('TL02','BH02',N'Sợi nhớ sợi thương')

INSERT INTO TACGIA(IDTacGia,HoTen,IDTheLoaiSoTruongNhat,IDBaiHatTieuBieuNhat)
VALUES (1,N'Trần Tiến','TL01','BH01'),
(2,N'Đỗ Nhuận','TL02','BH01'),
(3,N'Phan Huỳnh Điểu','TL02','BH02'),
(4,N'Vi Nhật Tảo','TL01','BH02')

UPDATE THELOAI SET IDBaiHatTieuBieu = 'BH01' WHERE IDTheLoai = 'TL01'
UPDATE THELOAI SET IDBaiHatTieuBieu = 'BH02' WHERE IDTheLoai = 'TL02'

UPDATE BAIHAT SET IDTacGia = 1 WHERE IDTheLoai = 'TL01' AND IDBaiHat = 'BH01'
UPDATE BAIHAT SET IDTacGia = 2 WHERE IDTheLoai = 'TL02' AND IDBaiHat = 'BH01'
UPDATE BAIHAT SET IDTacGia = 3 WHERE IDTheLoai = 'TL02' AND IDBaiHat = 'BH02'
UPDATE BAIHAT SET IDTacGia = 4 WHERE IDTheLoai = 'TL01' AND IDBaiHat = 'BH02'

--TRUY VAN
SELECT BAIHAT.TenBaiHat
FROM BAIHAT
JOIN THELOAI ON BAIHAT.IDTheLoai = THELOAI.IDTheLoai
JOIN TACGIA ON BAIHAT.IDTacGia = TACGIA.IDTacGia
WHERE THELOAI.TenTheLoai = N'Nhạc trữ tình'
AND TACGIA.HoTen = N'Đỗ Nhuận'

SELECT THELOAI.TenTheLoai
FROM THELOAI
LEFT JOIN BAIHAT ON THELOAI.IDTheLoai = BAIHAT.IDTheLoai
WHERE BAIHAT.IDBaiHat IS NULL


SELECT TACGIA.IDTacGia, TACGIA.HoTen, COUNT(BAIHAT.IDBaiHat) AS SoBaiHat
FROM TACGIA
LEFT JOIN BAIHAT ON TACGIA.IDTacGia = BAIHAT.IDTacGia
GROUP BY TACGIA.IDTacGia, TACGIA.HoTen

