USE QL_DeTai
--trigger (khong thi)
--mỗi giảng viên chỉ được tham gia tối đa 3 cviec trong 1 đề tài
--				T		X		S
--THAMGIADT		+		-		+ (MAGV,MADT)
GO
CREATE PROCEDURE THEM_PCONGDT
	@MAGV INT,
	@MADT INT,
	@STT INT
AS
BEGIN
	--ĐẾM SỐ CV TRONG @MAGV MÀ @MAGV ĐAG THAM GIA -> <3
	IF(SELECT COUNT(*) FROM THAMGIADT WHERE MAGV = @MAGV AND MADT = @MADT) < 3
	BEGIN
		INSERT INTO THAMGIADT (MAGV,MADT,STT) VALUES (@MAGV,@MADT,@STT)
		PRINT N'PHÂN CÔNG THÀNH CÔNG'
	END
	ELSE
	BEGIN
		RAISERROR(N'Không tham gia quá 3 cv trong 1 dtai',15,1)
		ROLLBACK
		RETURN
	END
END
GO
--TRIGGER THỰC THI KHI NÀO: KHI CHÚNG TA THỰC HIỆN LỆNH INSERT
--INSERT INTO THAMGIADT....
CREATE TRIGGER TGTHEMPCONG
ON THAMGIADT
FOR INSERT, UPDATE, DELETE
AS
BEGIN
	IF EXISTS(SELECT COUNT(*) FROM inserted i JOIN THAMGIADT t ON i.MAGV = t.MAGV AND i.MADT = t.MADT
	GROUP BY t.MAGV,t.MADT
	HAVING COUNT(*)>3)
	BEGIN
		RAISERROR(N'Không tham gia quá 3 cv trong 1 dtai',15,1)
		ROLLBACK
		RETURN
	END
	ELSE PRINT N'PHÂN CÔNG THÀNH CÔNG'
END
GO
INSERT INTO THAMGIADT(MAGV,MADT,STT) VALUES (015,002,1)
DELETE FROM THAMGIADT WHERE MAGV = 015 AND MADT = 002 AND STT = 1
UPDATE THAMGIADT SET PHUCAP = 100 WHERE MAGV = 008 AND MADT = 006
SELECT * FROM GIAOVIEN

--ôn tập: truy vấn nâng cao, mở rộng, stored, function
--truy vấn nâng cao: lồng (GROUP BY HAVING), phép chia, ...
--PHÉP CHIA
--CHO BIẾT MÃ SỐ, TÊN CỦA GVQLCM CỦA GV THAM GIA TẤT CẢ DT THUỘC CDE NCPT
--KẾT BẢNG ĐỂ LẤY THÊM THÔNG TIN GVQLCM CỦA HỌ

--CHO DS GV THAM GIA TẤT CẢ DT THUỘC CDE NCPT
--R: THAMGIADT(MAGV,MADT)
--S: MADT THUỘC CDE NCPT
--KQ: (MAGV)

--VỚI MỖI GV CÓ TGDT THUỘC CDE NCPT
--KHÔNG TỒN TẠI (TÌM DS DTAI THUỘC CDE NCPT MÀ GV NÀY CHƯA THAM GIA)
					--DS MADTAI THUỘC CDE NCPT
					--EXCEPT
					--DS DETAI THUỘC CDE NCPT CỦA GV(i)
SELECT DISTINCT R.MAGV,NQL.HOTEN AS N'NGƯỜI QUẢN LÝ'
FROM THAMGIADT R JOIN DETAI DT ON R.MADT = DT.MADT 
JOIN CHUDE CD ON CD.MACD = DT.MACD
JOIN GIAOVIEN GV ON R.MAGV = GV.MAGV
JOIN GIAOVIEN NQL ON NQL.MAGV = GV.GVQLCM
WHERE CD.TENCD = N'Nghiên cứu phát triển'
AND NOT EXISTS
(
	SELECT MADT FROM DETAI S JOIN CHUDE C ON S.MACD = C.MACD
	WHERE CD.TENCD = N'Nghiên cứu phát triển'
	EXCEPT
	SELECT T.MADT FROM THAMGIADT T 
	WHERE T.MADT = R.MADT AND T.MAGV = R.MAGV
)

--CHO DS CÁC DTAI ĐƯỢC TẤT CẢ GV CỦA BOMON HTTT THAM GIA
--R: THAMGIADT (MADT,MAGV)
--S: (MAGV) TẤT CẢ GV CỦA BM HTTT
--KQ: (MADT) (XUẤT CÁI GÌ)

--VỚI MỖI DTAI (XUẤT GÌ VỚI MỖI ĐÓ)
--KHÔNG TỒN TẠI (DS MAGV BM HTTT CHƯA THAM GIA DTAI NÀY)
					--S: (MAGV) TẤT CẢ GV CỦA BM HTTT
					--EXCEPT
					--DS MAGV BM HTTT ĐÃ THAM GIA DTAI NÀY
SELECT MADT
FROM THAMGIADT R JOIN GIAOVIEN GV ON R.MAGV = GV.MAGV
WHERE GV.MABM = 'HTTT'
AND NOT EXISTS
(
	SELECT MAGV
	FROM GIAOVIEN GV
	WHERE GV.MABM = 'HTTT'
	EXCEPT
	SELECT t.MAGV
	FROM THAMGIADT t JOIN GIAOVIEN g ON t.MAGV = g.MAGV
	WHERE MADT = R.MADT AND g.MABM = 'HTTT'
)

--CHO DS CÁC CHỦ ĐỀ ĐƯỢC TẤT CẢ GV BM HTTT THAM GIA
--R: MACD
--S: TẤT CẢ GV BM HTTT (MAGV)
--KQ: MACD
--VỚI MỖI CDE (XUẤT GÌ VỚI MỖI ĐÓ)
--KHÔNG TỒN TẠI (DS MAGV BM HTTT CHƯA THAM GIA DTAI NÀY)
					--S: (MAGV) TẤT CẢ GV CỦA BM HTTT
					--EXCEPT
					--DS MAGV BM HTTT ĐÃ THAM GIA CDE NÀY

SELECT DISTINCT R.*
FROM CHUDE R JOIN DETAI DT ON R.MACD = DT.MACD JOIN THAMGIADT TGDT ON DT.MADT = TGDT.MADT JOIN GIAOVIEN GV ON GV.MAGV = TGDT.MAGV
WHERE GV.MABM = 'HTTT'
AND NOT EXISTS
(
	SELECT MAGV
	FROM GIAOVIEN GV
	WHERE GV.MABM = 'HTTT'
	EXCEPT
	SELECT g.MAGV
	FROM CHUDE CD JOIN DETAI dt ON CD.MACD = dt.MACD JOIN THAMGIADT t ON dt.MADT = t.MADT JOIN GIAOVIEN g ON g.MAGV = t.MAGV
	WHERE R.MACD = CD.MACD AND g.MABM = 'HTTT'
)

--dặn dò thi
