USE QL_DeTai

--GROUP BY + HAVING
--voi moi bm, dem so gv
SELECT gv.MABM, bm.TENBM,COUNT(gv.MAGV) AS SO_LUONG
FROM GiAOVIEN gv JOIN BOMON bm ON gv.MABM = bm.MABM
GROUP BY gv.MABM, bm.TENBM
HAVING COUNT(gv.MAGV) < 2
ORDER BY SO_LUONG --doi tuong dem (gom nhom) khong xuat hien tren select

--Q27
SELECT COUNT(gv.MAGV) AS SLG_GV, SUM(gv.LUONG) AS TONG_LUONG
FROM GiAOVIEN gv

--Q28
SELECT gv.MABM,COUNT(gv.MAGV) AS SLG_GV, AVG(gv.LUONG) AS TB_LUONG
FROM GIAOVIEN gv
GROUP BY gv.MABM

--Q29
SELECT cd.TENCD, COUNT(dt.MADT) AS SODT
FROM CHUDE cd JOIN DETAI dt ON cd.MACD = dt.MACD
GROUP BY cd.TENCD --Dem theo key khong theo ten vi trung se sai

--Q30
SELECT gv.HOTEN, COUNT(DISTINCT(tgdt.MADT)) AS SLG_DT
FROM GIAOVIEN gv JOIN THAMGIADT tgdt ON tgdt.MAGV = gv.MAGV 
GROUP BY gv.HOTEN

--Q31
SELECT gv.HOTEN, COUNT(dt.GVCNDT)
FROM GIAOVIEN gv JOIN DETAI dt ON dt.GVCNDT = gv.MAGV 
GROUP BY gv.HOTEN