USE QL_DeTai
GO

--Q58. Cho biết tên giáo viên nào mà tham gia đề tài đủ tất cả các chủ đề
--CHIA: TẤT CẢ CÁC CHỦ ĐỀ
--BỊ CHIA: CÁC CHỦ ĐỀ MÀ GIÁO VIÊN THAM GIA
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT CHUDE.MACD FROM CHUDE
    EXCEPT
    SELECT DT.MACD 
    FROM DETAI DT, THAMGIADT TGDT
    WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT
)
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT * FROM CHUDE CD
    WHERE NOT EXISTS (
        SELECT * 
        FROM DETAI DT, THAMGIADT TGDT
        WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT AND CD.MACD = DT.MACD
    )
)

--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TGDT, DETAI DT
WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT DT.MACD) = (
    SELECT COUNT(CHUDE.MACD)
    FROM CHUDE
)

--Q59. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn HTTT tham gia.
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN CỦA BỘ MÔN HTTT THAM GIA
--EXCEPT
SELECT DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS( 
    SELECT GV.MAGV
    FROM GIAOVIEN GV
    WHERE GV.MABM = 'HTTT'
    EXCEPT
    SELECT TGDT.MAGV
    FROM THAMGIADT TGDT
    WHERE TGDT.MADT = DT1.MADT
)
--NOT EXISTS
SELECT DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS( 
    SELECT *
    FROM GIAOVIEN GV
    WHERE GV.MABM = 'HTTT' AND NOT EXISTS (
        SELECT *
        FROM THAMGIADT TGDT
        WHERE TGDT.MADT = DT1.MADT AND GV.MAGV = TGDT.MAGV
    )
)

--COUNT
SELECT DT.TENDT
FROM DETAI DT, GIAOVIEN GV, THAMGIADT TG
WHERE GV.MABM = 'HTTT' AND GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (
    SELECT COUNT(GV2.MAGV) 
    FROM GIAOVIEN GV2
    WHERE GV2.MABM = 'HTTT'
)


--Q60. Cho biết tên đề tài có tất cả giảng viên bộ môn “Hệ thống thông tin” tham gia
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ TẤT CẢ GIẢNG VIÊN BỘ MÔN HỆ THỐNG THÔNG TIN THAM GIA
--EXCEPT
SELECT DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS( 
    SELECT GV.MAGV
    FROM GIAOVIEN GV, BOMON BM
    WHERE BM.TENBM = N'Hệ thống thông tin' AND BM.MABM = GV.MABM
    EXCEPT
    SELECT TGDT.MAGV
    FROM THAMGIADT TGDT
    WHERE TGDT.MADT = DT1.MADT
)
-- NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT, GIAOVIEN GV, THAMGIADT TG, BOMON BM
WHERE BM.TENBM = N'Hệ thống thông tin' AND GV.MABM = BM.MABM AND GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (
    SELECT COUNT(GV2.MAGV) 
    FROM GIAOVIEN GV2, BOMON BM2
    WHERE BM2.TENBM = N'Hệ thống thông tin' AND GV2.MABM = BM2.MABM
)
-- COUNT
SELECT DT.TENDT
FROM DETAI DT, GIAOVIEN GV, THAMGIADT TG, BOMON BM
WHERE BM.TENBM = N'Hệ thống thông tin' AND GV.MABM = BM.MABM AND GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (
    SELECT COUNT(GV2.MAGV) 
    FROM GIAOVIEN GV2, BOMON BM2
    WHERE BM2.TENBM = N'Hệ thống thông tin' AND GV2.MABM = BM2.MABM
)
--Q61. Cho biết giáo viên nào đã tham gia tất cả các đề tài có mã chủ đề là QLGD.
--CHIA: TÁT CẢ CÁC ĐỀ TÀI 
--BỊ CHIA: CÁC ĐỀ TÀI CÓ MÃ CHỦ ĐỀ LÀ QLGD
-- EXCEPT
SELECT DISTINCT TG1.MAGV, GV.HOTEN
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV AND NOT EXISTS (
    SELECT MADT FROM DETAI WHERE MACD = N'QLGD'
    EXCEPT
    SELECT MADT
    FROM THAMGIADT TG2
    WHERE TG2.MAGV = TG1.MAGV
)
--NOT EXIST
SELECT DISTINCT TG1.MAGV, GV.HOTEN
FROM THAMGIADT TG1, GIAOVIEN GV
WHERE TG1.MAGV = GV.MAGV AND NOT EXISTS (
    SELECT * FROM DETAI DT WHERE DT.MACD = N'QLGD' AND NOT EXISTS (
        SELECT *
        FROM THAMGIADT TG2
        WHERE TG2.MAGV = TG1.MAGV AND DT.MADT = TG2.MADT
    )
)
--COUNT
SELECT GV1.HOTEN
FROM GIAOVIEN GV1, THAMGIADT TG1, DETAI DT1
WHERE GV1.MAGV = TG1.MAGV AND TG1.MADT = DT1.MADT AND DT1.MACD = N'QLGD'
GROUP BY GV1.HOTEN
HAVING COUNT (DISTINCT DT1.MADT) = (
    SELECT COUNT(DT2.MACD)
    FROM DETAI DT2
    WHERE DT2.MACD = N'QLGD'
)
--Q62. Cho biết tên giáo viên nào tham gia tất cả các đề tài mà giáo viên Trần Trà Hương đã tham gia.
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN TRẦN TRÀ HƯƠNG ĐÃ THAM GIA
--EXCEPT
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE GV1.HOTEN != N'Trần Trà Hương' AND NOT EXISTS( 
    SELECT TGDT.MADT
    FROM THAMGIADT TGDT, GIAOVIEN GV
    WHERE GV.HOTEN = N'Trần Trà Hương' AND GV.MAGV = TGDT.MAGV
    EXCEPT
    SELECT TGDT2.MADT
    FROM THAMGIADT TGDT2
    WHERE GV1.MAGV = TGDT2.MAGV
);

-- NOT EXISTS
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE GV1.HOTEN != N'Trần Trà Hương' AND NOT EXISTS( 
    SELECT TGDT.MADT
    FROM THAMGIADT TGDT, GIAOVIEN GV
    WHERE GV.HOTEN = N'Trần Trà Hương' AND GV.MAGV = TGDT.MAGV AND NOT EXISTS (
        SELECT TGDT2.MADT
        FROM THAMGIADT TGDT2
        WHERE GV1.MAGV = TGDT2.MAGV AND TGDT.MADT = TGDT2.MADT
    )
)
--COUNT
SELECT GV2.HOTEN
FROM GIAOVIEN GV2, THAMGIADT TG2
WHERE GV2.HOTEN != N'Trần Trà Hương' AND GV2.MAGV = TG2.MAGV AND TG2.MADT IN (
    SELECT TG1.MADT
    FROM GIAOVIEN GV1, THAMGIADT TG1
    WHERE GV1.HOTEN = N'Trần Trà Hương' AND GV1.MAGV = TG1.MAGV
)
GROUP BY GV2.HOTEN
HAVING COUNT(DISTINCT TG2.MADT) = (
    SELECT COUNT(TG1.MADT)
    FROM GIAOVIEN GV1, THAMGIADT TG1
    WHERE GV1.HOTEN = N'Trần Trà Hương' AND GV1.MAGV = TG1.MAGV
)
-- Q63. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn Hóa Hữu Cơ tham gia.
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN CỦA BỘ MÔN HÓA HỮU CƠ THAM GIA
-- EXCEPT
SELECT DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS (
    SELECT GV.MAGV
    FROM GIAOVIEN GV, BOMON BM
    WHERE BM.TENBM = N'Hóa hữu cơ' AND BM.MABM = GV.MABM
    EXCEPT
    SELECT TGDT.MAGV
    FROM THAMGIADT TGDT
    WHERE TGDT.MADT = DT1.MADT
);

-- NOT EXISTS
SELECT DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS (
    SELECT GV.MAGV
    FROM GIAOVIEN GV, BOMON BM
    WHERE BM.TENBM = N'Hóa hữu cơ' AND BM.MABM = GV.MABM
    AND NOT EXISTS (
        SELECT TGDT.MAGV
        FROM THAMGIADT TGDT
        WHERE TGDT.MADT = DT1.MADT AND GV.MAGV = TGDT.MAGV
    )
);

-- COUNT
SELECT DT1.TENDT
FROM DETAI DT1, THAMGIADT TG1
WHERE TG1.MAGV IN (
    SELECT GV1.MAGV
    FROM GIAOVIEN GV1, BOMON BM1
    WHERE BM1.TENBM = N'Hóa hữu cơ' AND BM1.MABM = GV1.MABM
)
GROUP BY DT1.TENDT
HAVING COUNT(DISTINCT TG1.MAGV) = (
    SELECT COUNT(GV2.MAGV)
    FROM GIAOVIEN GV2, BOMON BM2
    WHERE BM2.TENBM = N'Hóa hữu cơ' AND BM2.MABM = GV2.MABM
);

-- Q64. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài 006.
--CHIA: TẤT CẢ CÁC CÔNG VIỆC
--BỊ CHIA: CÁC CÔNG VIỆC MÀ GIÁO VIÊN THAM GIA CỦA ĐỀ TÀI 006
-- EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT CV.SOTT
    FROM CONGVIEC CV
    WHERE CV.MADT = '006'
    EXCEPT
    SELECT TGDT.STT
    FROM THAMGIADT TGDT
    WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = '006'
);

-- NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT *
    FROM CONGVIEC CV
    WHERE CV.MADT = '006'
    AND NOT EXISTS (
        SELECT *
        FROM THAMGIADT TGDT
        WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = '006' AND CV.STT = TGDT.STT
    )
);

-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT = '006'
GROUP BY GV.HOTEN
HAVING COUNT(DISTINCT TG.STT) = (
    SELECT COUNT(CV.SOTT)
    FROM CONGVIEC CV
    WHERE CV.MADT = '006'
);

-- Q65. Cho biết giáo viên nào đã tham gia tất cả các đề tài của chủ đề Ứng dụng công nghệ.
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN THAM GIA CHỦ ĐỀ ỨNG DỤNG CÔNG NGHỆ
-- EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT DT.MADT
    FROM DETAI DT, CHUDE CD
    WHERE CD.TENCD = N'Ứng dụng công nghệ' AND CD.MACD = DT.MACD
    EXCEPT
    SELECT TGDT.MADT
    FROM THAMGIADT TGDT
    WHERE TGDT.MAGV = GV.MAGV
);

-- NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT *
    FROM DETAI DT, CHUDE CD
    WHERE CD.TENCD = N'Ứng dụng công nghệ' AND CD.MACD = DT.MACD
    AND NOT EXISTS (
        SELECT *
        FROM THAMGIADT TGDT
        WHERE TGDT.MAGV = GV.MAGV AND DT.MADT = TGDT.MADT
    )
);

-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, CHUDE CD, DETAI DT
WHERE CD.TENCD = N'Ứng dụng công nghệ' AND CD.MACD = DT.MACD AND DT.MADT = TG.MADT AND TG.MAGV = GV.MAGV
GROUP BY GV.HOTEN
HAVING COUNT(DISTINCT TG.STT) = (
    SELECT COUNT(DT.MADT)
    FROM DETAI DT, CHUDE CD
    WHERE CD.TENCD = N'Ứng dụng công nghệ' AND CD.MACD = DT.MACD
);

-- Q66. Cho biết tên giáo viên nào đã tham gia tất cả các đề tài do Trần Trà Hương làm chủ nhiệm.
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN THAM GIA DO TRẦN TRÀ HƯƠNG LÀM CHỦ NHIỆM
-- EXCEPT
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
    SELECT DT.MADT
    FROM DETAI DT, GIAOVIEN GV
    WHERE GV.HOTEN = N'Trần Trà Hương' AND GV.MAGV = DT.GVCNDT
    EXCEPT
    SELECT TGDT.MADT
    FROM THAMGIADT TGDT
    WHERE TGDT.MAGV = GV1.MAGV
);

-- NOT EXISTS
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
    SELECT DT.MADT
    FROM DETAI DT, GIAOVIEN GV
    WHERE GV.HOTEN = N'Trần Trà Hương' AND GV.MAGV = DT.GVCNDT
    AND NOT EXISTS (
        SELECT TGDT.MADT
        FROM THAMGIADT TGDT
        WHERE TGDT.MAGV = GV1.MAGV AND DT.MADT = TGDT.MADT
    )
);

-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT IN (
    SELECT DT.MADT
    FROM DETAI DT, GIAOVIEN GV
    WHERE GV.HOTEN = N'Trần Trà Hương' AND GV.MAGV = DT.GVCNDT
)
GROUP BY GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (
    SELECT COUNT(DT.MADT)
    FROM DETAI DT, GIAOVIEN GV
    WHERE GV.HOTEN = N'Trần Trà Hương' AND GV.MAGV = DT.GVCNDT
);

-- Q67. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa CNTT tham gia.
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN CNTT THAM GIA
-- EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
    SELECT GV.MAGV
    FROM GIAOVIEN GV, BOMON BM, KHOA K
    WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.MAKHOA = N'CNTT'
    EXCEPT
    SELECT TGDT.MAGV
    FROM THAMGIADT TGDT
    WHERE TGDT.MADT = DT.MADT
);

-- NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
    SELECT *
    FROM GIAOVIEN GV, BOMON BM, KHOA K
    WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.MAKHOA = N'CNTT'
    AND NOT EXISTS (
        SELECT *
        FROM THAMGIADT TGDT
        WHERE TGDT.MADT = DT.MADT AND GV.MAGV = TGDT.MAGV
    )
);

-- COUNT
SELECT DT.TENDT
FROM DETAI DT, THAMGIADT TG
WHERE DT.MADT = TG.MADT AND TG.MAGV IN (
    SELECT GV.MAGV
    FROM GIAOVIEN GV, BOMON BM, KHOA K
    WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.MAKHOA = N'CNTT'
)
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (
    SELECT COUNT(GV.MAGV)
    FROM GIAOVIEN GV, BOMON BM, KHOA K
    WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.MAKHOA = N'CNTT'
);

-- Q68. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài Nghiên cứu tế bào gốc.
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN TRẦN TRÀ HƯƠNG ĐÃ THAM GIA
-- EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT CV.SOTT
    FROM CONGVIEC CV, DETAI DT
    WHERE DT.TENDT = N'Nghiên cứu tế bào gốc' AND DT.MADT = CV.MADT
    EXCEPT
    SELECT TGDT.STT
    FROM THAMGIADT TGDT, DETAI DT2
    WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc' AND DT2.MADT = TGDT.MADT AND GV.MAGV = TGDT.MAGV
);

-- NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT *
    FROM CONGVIEC CV, DETAI DT
    WHERE DT.TENDT = N'Nghiên cứu tế bào gốc' AND DT.MADT = CV.MADT
    AND NOT EXISTS (
        SELECT *
        FROM THAMGIADT TGDT, DETAI DT2
        WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc' AND DT2.MADT = TGDT.MADT
        AND GV.MAGV = TGDT.MAGV AND TGDT.STT = CV.SOTT
    )
);

-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, DETAI DT, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY GV.HOTEN
HAVING COUNT(DISTINCT TG.STT) = (
    SELECT COUNT(CV.SOTT)
    FROM CONGVIEC CV, DETAI DT1
    WHERE DT1.TENDT = N'Nghiên cứu tế bào gốc' AND DT1.MADT = CV.MADT
);

-- Q69. Tìm tên các giáo viên được phân công làm tất cả các đề tài có kinh phí trên 100 triệu?
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN ĐƯỢC PHÂN CÔNG CÓ KINH PHÍ TRÊN 100 TRIỆU
-- EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT DT.MADT
    FROM DETAI DT
    WHERE DT.KINHPHI > 1000
    EXCEPT
    SELECT TGDT.MADT
    FROM THAMGIADT TGDT
    WHERE GV.MAGV = TGDT.MAGV
);

-- NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT *
    FROM DETAI DT
    WHERE DT.KINHPHI > 1000
    AND NOT EXISTS (
        SELECT *
        FROM THAMGIADT TGDT
        WHERE GV.MAGV = TGDT.MAGV AND DT.MADT = TGDT.MADT
    )
);

-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT IN (
    SELECT DT1.MADT
    FROM DETAI DT1
    WHERE DT1.KINHPHI > 1000
)
GROUP BY GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (
    SELECT COUNT(DT1.MADT)
    FROM DETAI DT1
    WHERE DT1.KINHPHI > 1000
);

-- Q70. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa Sinh Học tham gia.
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN CỦA KHOA SINH HỌC THAM GIA
-- EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
    SELECT GV.MAGV
    FROM GIAOVIEN GV, BOMON BM, KHOA K
    WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học'
    EXCEPT
    SELECT TGDT.MAGV
    FROM THAMGIADT TGDT
    WHERE TGDT.MADT = DT.MADT
);

-- NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
    SELECT *
    FROM GIAOVIEN GV, BOMON BM, KHOA K
    WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học'
    AND NOT EXISTS (
        SELECT *
        FROM THAMGIADT TGDT
        WHERE TGDT.MADT = DT.MADT AND GV.MAGV = TGDT.MAGV
    )
);

-- COUNT
SELECT DT.TENDT
FROM DETAI DT, THAMGIADT TG
WHERE DT.MADT = TG.MADT AND TG.MAGV IN (
    SELECT GV.MAGV
    FROM GIAOVIEN GV, BOMON BM, KHOA K
    WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học'
)
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (
    SELECT COUNT(GV.MAGV)
    FROM GIAOVIEN GV, BOMON BM, KHOA K
    WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học'
);

-- Q71. Cho biết mã số, họ tên, ngày sinh của giáo viên tham gia tất cả các công việc của đề tài “Ứng dụng hóa học xanh”.
--CHIA: TẤT CẢ CÁC CÔNG VIỆC
--BỊ CHIA: CÁC CÔNG VIỆC MÀ GIÁO VIÊN THAM GIA CỦA ĐỀ TÀI ỨNG DỤNG HÓA HỌC XANH
-- EXCEPT
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT CV.SOTT
    FROM CONGVIEC CV, DETAI DT
    WHERE DT.TENDT = N'Ứng dụng hóa học xanh' AND DT.MADT = CV.MADT
    EXCEPT
    SELECT TGDT.STT
    FROM THAMGIADT TGDT, DETAI DT2
    WHERE DT2.TENDT = N'Ứng dụng hóa học xanh' AND DT2.MADT = TGDT.MADT AND GV.MAGV = TGDT.MAGV
);

-- NOT EXISTS
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT CV.SOTT
    FROM CONGVIEC CV, DETAI DT
    WHERE DT.TENDT = N'Ứng dụng hóa học xanh' AND DT.MADT = CV.MADT
    AND NOT EXISTS (
        SELECT TGDT.STT
        FROM THAMGIADT TGDT, DETAI DT2
        WHERE DT2.TENDT = N'Ứng dụng hóa học xanh' AND DT2.MADT = TGDT.MADT AND GV.MAGV = TGDT.MAGV AND CV.SOTT = TGDT.STT
    )
);

-- COUNT
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV, DETAI DT, THAMGIADT TG
WHERE DT.TENDT = N'Ứng dụng hóa học xanh' AND TG.MADT = DT.MADT
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(DISTINCT TG.STT) = (
    SELECT COUNT(CV.SOTT)
    FROM CONGVIEC CV, DETAI DT
    WHERE DT.TENDT = N'Ứng dụng hóa học xanh' AND DT.MADT = CV.MADT
);

-- Q72. Cho biết mã số, họ tên, tên bộ môn và tên người quản lý chuyên môn của giáo viên tham gia tất cả các đề tài thuộc chủ đề “Nghiên cứu phát triển”.
--CHIA: TẤT CẢ CÁC ĐỀ TÀI
--BỊ CHIA: CÁC ĐỀ TÀI MÀ GIÁO VIÊN THAM GIA THUỘC CHỦ ĐỀ NGHIÊN CỨU PHÁT TRIỂN
-- EXCEPT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQLBM.HOTEN
FROM GIAOVIEN GV, GIAOVIEN GVQLBM, BOMON BM
WHERE GV.MABM = BM.MABM AND GV.GVQLCM = GVQLBM.MAGV
AND NOT EXISTS (
    SELECT DT.MADT
    FROM DETAI DT, CHUDE CD
    WHERE CD.TENCD = N'Nghiên cứu phát triển' AND CD.MACD = DT.MACD
    EXCEPT
    SELECT TGDT.MADT
    FROM THAMGIADT TGDT
    WHERE TGDT.MAGV = GV.MAGV
);

-- NOT EXISTS
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQLBM.HOTEN
FROM GIAOVIEN GV, GIAOVIEN GVQLBM, BOMON BM
WHERE GV.MABM = BM.MABM AND GV.GVQLCM = GVQLBM.MAGV
AND NOT EXISTS (
    SELECT *
    FROM DETAI DT, CHUDE CD
    WHERE CD.TENCD = N'Nghiên cứu phát triển' AND CD.MACD = DT.MACD
    AND NOT EXISTS (
        SELECT *
        FROM THAMGIADT TGDT
        WHERE TGDT.MAGV = GV.MAGV AND DT.MADT = TGDT.MADT
    )
);

-- COUNT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQLBM.HOTEN
FROM GIAOVIEN GV, GIAOVIEN GVQLBM, BOMON BM, THAMGIADT TG, CHUDE CD, DETAI DT
WHERE GV.MABM = BM.MABM AND GV.GVQLCM = GVQLBM.MAGV AND TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT
AND DT.TENDT = N'Nghiên cứu phát triển'
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, GVQLBM.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (
    SELECT COUNT(DT1.MADT)
    FROM DETAI DT1, CHUDE CD1
    WHERE CD1.TENCD = N'Nghiên cứu phát triển' AND CD1.MACD = DT1.MACD
);
